version: 2

partial:
  by: target

builds:
  - main: ./cmd/iron-proxy
    binary: iron-proxy
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - netgo
      - osusergo
    ldflags:
      - -s -w -X github.com/ironsh/iron-proxy/internal/version.Version={{.Version}} {{ if eq .Os "linux" }}-extldflags=-static{{ end }}

archives:
  - formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers_v2:
  - images:
      - "ironsh/iron-proxy"
    tags:
      - "{{ .Version }}"
      - "latest"
    dockerfile: Dockerfile.release

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
