services:
  connect-api:
    image: 1password/connect-api:latest
    network_mode: host
    environment:
      OP_HTTP_PORT: "8080"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json:ro"
      - "data:/home/opuser/.op/data"
    restart: unless-stopped

  connect-sync:
    image: 1password/connect-sync:latest
    network_mode: host
    environment:
      OP_HTTP_PORT: "8081"
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json:ro"
      - "data:/home/opuser/.op/data"
    restart: unless-stopped

volumes:
  data:
